### ISSUE TITLE
Is there a way to customize the error message ?

### ISSUE THREAD

**Issue by mohanraj-r** [JulienKode/pull-request-name-linter-action#50]
I would like to customize the error message to provide links/references to doc as right now even I forget at times and get lost as to what needs to be done. Is there a way to customize the error message currently ?

**Comment by JulienKode** [comment]
Hi @mohanraj-r ,

Thanks for contributing ! 😊

For the moment there is no way to customize the error message because we simply show the error of commitlint 
https://github.com/JulienKode/pull-request-name-linter-action/blob/239b27e46c06b8b7cd6cab2ce989ba645700cd88/src/main.ts#L40

- What kind of api did you like to customize the message ? 
- Why the commitlint messages does not fits your need ? May be you want to display the error message + a link to solve the issue lint issue ? 🤔

**Comment by mohanraj-r** [comment]
Thanks @JulienKode 
Yes an optional text (that users can supply with links to docs etc) to establish context so that what needs to be done to fix the error can be better understood. So if the text is give it should prefix the `result.errors`

**Comment by JulienKode** [comment]
It's sounds a pretty good idea @mohanraj-r 😊

**Comment by JulienKode** [comment]
We can close it as we do not have for now a precise idea of what we need on this feature

If anyone think it needs to be implemented feel free to re-open it 😊

**Comment by BenK93** [comment]
> Thanks @JulienKode Yes an optional text (that users can supply with links to docs etc) to establish context so that what needs to be done to fix the error can be better understood. So if the text is given it should prefix the `result.errors`

Agree very much! too bad there isn't a way to customize the error message.
for example the error message in [https://github.com/wagoid/commitlint-github-action](https://github.com/wagoid/commitlint-github-action)
is really descriptive.
eg: 
<img width="499" alt="Screenshot 2023-03-19 at 14 43 05" src="https://user-images.githubusercontent.com/21170255/226175916-028d8130-f9d0-4546-a8dc-f92a02364e4e.png">
